In [ ]:
a = rand(4,4)

In [ ]:
reshape(a,2,8)

In [8]:
reshape(a,8,2)

8×2 Array{Float64,2}:
 0.900981  0.982234  
 0.297646  0.482789  
 0.126409  0.400219  
 0.785981  0.220764  
 0.325316  6.14355e-6
 0.238539  0.691941  
 0.344719  0.930616  
 0.955046  0.793634  

In [25]:
b = [true false false false;false true false false;false false true false;false false false true]

4×4 Array{Bool,2}:
  true  false  false  false
 false   true  false  false
 false  false   true  false
 false  false  false   true

In [26]:
a[b]

4-element Array{Float64,1}:
 0.900981
 0.238539
 0.400219
 0.793634

In [28]:
a.*b

4×4 Array{Float64,2}:
 0.900981  0.0       0.0       0.0     
 0.0       0.238539  0.0       0.0     
 0.0       0.0       0.400219  0.0     
 0.0       0.0       0.0       0.793634

In [29]:
a*eye(4)

4×4 Array{Float64,2}:
 0.900981  0.325316  0.982234  6.14355e-6
 0.297646  0.238539  0.482789  0.691941  
 0.126409  0.344719  0.400219  0.930616  
 0.785981  0.955046  0.220764  0.793634  

In [35]:
a.*eye(4)

4×4 Array{Float64,2}:
 0.900981  0.0       0.0       0.0     
 0.0       0.238539  0.0       0.0     
 0.0       0.0       0.400219  0.0     
 0.0       0.0       0.0       0.793634

In [43]:
a.*eye(4)*ones(4,1)

4×1 Array{Float64,2}:
 0.900981
 0.238539
 0.400219
 0.793634

In [11]:
c=rand(8)


8-element Array{Float64,1}:
 0.108331
 0.157961
 0.191658
 0.910859
 0.654824
 0.296979
 0.210386
 0.687958

In [12]:
length(c)

8

In [13]:
i = 1;
while i <= length(c)
    println(c[i])
    if c[i] > 0.8
        break
    end
    i=i+1
end

0.1083314156877031
0.1579610683694097
0.1916576210037273
0.9108594979954163
